// TELC B1 Vocabulary — sorted by frequency rank (rank 1 = most frequent)
// For nouns: includes article (der/die/das)
// English field: multiple accepted translations separated by " / "

const WORDS = [
  // ── Rank 1–30: Core everyday vocabulary ─────────────────────────────
  { id: 1,   rank: 1,   de: "die Arbeit",                en: "work / job" },
  { id: 2,   rank: 2,   de: "das Geld",                  en: "money" },
  { id: 3,   rank: 3,   de: "die Zeit",                  en: "time" },
  { id: 4,   rank: 4,   de: "das Jahr",                  en: "year" },
  { id: 5,   rank: 5,   de: "der Tag",                   en: "day" },
  { id: 6,   rank: 6,   de: "der Mensch",                en: "person / human being" },
  { id: 7,   rank: 7,   de: "das Kind",                  en: "child" },
  { id: 8,   rank: 8,   de: "die Frau",                  en: "woman / wife" },
  { id: 9,   rank: 9,   de: "der Mann",                  en: "man / husband" },
  { id: 10,  rank: 10,  de: "das Haus",                  en: "house" },
  { id: 11,  rank: 11,  de: "die Familie",               en: "family" },
  { id: 12,  rank: 12,  de: "die Stadt",                 en: "city / town" },
  { id: 13,  rank: 13,  de: "das Land",                  en: "country / land" },
  { id: 14,  rank: 14,  de: "das Leben",                 en: "life" },
  { id: 15,  rank: 15,  de: "die Woche",                 en: "week" },
  { id: 16,  rank: 16,  de: "die Sprache",               en: "language" },
  { id: 17,  rank: 17,  de: "der Beruf",                 en: "profession / job" },
  { id: 18,  rank: 18,  de: "die Schule",                en: "school" },
  { id: 19,  rank: 19,  de: "die Straße",                en: "street / road" },
  { id: 20,  rank: 20,  de: "das Auto",                  en: "car" },
  { id: 21,  rank: 21,  de: "das Wetter",                en: "weather" },
  { id: 22,  rank: 22,  de: "die Wohnung",               en: "apartment / flat" },
  { id: 23,  rank: 23,  de: "die Frage",                 en: "question" },
  { id: 24,  rank: 24,  de: "die Antwort",               en: "answer" },
  { id: 25,  rank: 25,  de: "das Problem",               en: "problem" },
  { id: 26,  rank: 26,  de: "die Möglichkeit",           en: "possibility / opportunity" },
  { id: 27,  rank: 27,  de: "der Grund",                 en: "reason / ground" },
  { id: 28,  rank: 28,  de: "die Reise",                 en: "trip / journey" },
  { id: 29,  rank: 29,  de: "das Beispiel",              en: "example" },
  { id: 30,  rank: 30,  de: "die Erfahrung",             en: "experience" },

  // ── Rank 31–50: Work & profession ───────────────────────────────────
  { id: 31,  rank: 31,  de: "das Büro",                  en: "office" },
  { id: 32,  rank: 32,  de: "der Chef",                  en: "boss / manager" },
  { id: 33,  rank: 33,  de: "der Kollege",               en: "colleague" },
  { id: 34,  rank: 34,  de: "die Ausbildung",            en: "vocational training / education" },
  { id: 35,  rank: 35,  de: "das Studium",               en: "studies / degree" },
  { id: 36,  rank: 36,  de: "die Bewerbung",             en: "job application" },
  { id: 37,  rank: 37,  de: "der Lebenslauf",            en: "CV / resume" },
  { id: 38,  rank: 38,  de: "das Vorstellungsgespräch",  en: "job interview" },
  { id: 39,  rank: 39,  de: "das Gehalt",                en: "salary" },
  { id: 40,  rank: 40,  de: "die Überstunden",           en: "overtime" },
  { id: 41,  rank: 41,  de: "der Urlaub",                en: "vacation / holiday" },
  { id: 42,  rank: 42,  de: "der Vertrag",               en: "contract" },
  { id: 43,  rank: 43,  de: "die Kündigung",             en: "termination / notice" },
  { id: 44,  rank: 44,  de: "das Praktikum",             en: "internship" },
  { id: 45,  rank: 45,  de: "die Stelle",                en: "position / post" },
  { id: 46,  rank: 46,  de: "die Kenntnisse",            en: "knowledge / skills" },
  { id: 47,  rank: 47,  de: "die Besprechung",           en: "meeting / discussion" },
  { id: 48,  rank: 48,  de: "die Aufgabe",               en: "task / assignment" },
  { id: 49,  rank: 49,  de: "der Betrieb",               en: "company / operation" },
  { id: 50,  rank: 50,  de: "die Abteilung",             en: "department" },

  // ── Rank 51–65: Education ────────────────────────────────────────────
  { id: 51,  rank: 51,  de: "die Universität",           en: "university" },
  { id: 52,  rank: 52,  de: "der Unterricht",            en: "lesson / class" },
  { id: 53,  rank: 53,  de: "die Prüfung",               en: "exam / test" },
  { id: 54,  rank: 54,  de: "die Note",                  en: "grade / mark" },
  { id: 55,  rank: 55,  de: "das Zeugnis",               en: "certificate / report card" },
  { id: 56,  rank: 56,  de: "der Kurs",                  en: "course" },
  { id: 57,  rank: 57,  de: "die Hausaufgabe",           en: "homework" },
  { id: 58,  rank: 58,  de: "das Wörterbuch",            en: "dictionary" },
  { id: 59,  rank: 59,  de: "die Bibliothek",            en: "library" },
  { id: 60,  rank: 60,  de: "der Abschluss",             en: "graduation / qualification" },

  // ── Rank 61–75: Health ───────────────────────────────────────────────
  { id: 61,  rank: 61,  de: "die Gesundheit",            en: "health" },
  { id: 62,  rank: 62,  de: "das Krankenhaus",           en: "hospital" },
  { id: 63,  rank: 63,  de: "der Arzt",                  en: "doctor / physician" },
  { id: 64,  rank: 64,  de: "die Krankheit",             en: "illness / disease" },
  { id: 65,  rank: 65,  de: "das Fieber",                en: "fever" },
  { id: 66,  rank: 66,  de: "der Schmerz",               en: "pain" },
  { id: 67,  rank: 67,  de: "die Allergie",              en: "allergy" },
  { id: 68,  rank: 68,  de: "das Medikament",            en: "medication / medicine" },
  { id: 69,  rank: 69,  de: "das Rezept",                en: "prescription / recipe" },
  { id: 70,  rank: 70,  de: "die Apotheke",              en: "pharmacy" },
  { id: 71,  rank: 71,  de: "der Termin",                en: "appointment" },
  { id: 72,  rank: 72,  de: "die Versicherung",          en: "insurance" },
  { id: 73,  rank: 73,  de: "die Krankenversicherung",   en: "health insurance" },
  { id: 74,  rank: 74,  de: "der Krankenwagen",          en: "ambulance" },
  { id: 75,  rank: 75,  de: "die Notaufnahme",           en: "emergency room" },

  // ── Rank 76–95: Transport & travel ──────────────────────────────────
  { id: 76,  rank: 76,  de: "der Zug",                   en: "train" },
  { id: 77,  rank: 77,  de: "der Bahnhof",               en: "train station" },
  { id: 78,  rank: 78,  de: "das Flugzeug",              en: "airplane" },
  { id: 79,  rank: 79,  de: "der Flughafen",             en: "airport" },
  { id: 80,  rank: 80,  de: "die U-Bahn",                en: "subway / underground" },
  { id: 81,  rank: 81,  de: "der Bus",                   en: "bus" },
  { id: 82,  rank: 82,  de: "die Fahrkarte",             en: "ticket" },
  { id: 83,  rank: 83,  de: "die Rückfahrkarte",         en: "return ticket" },
  { id: 84,  rank: 84,  de: "die Verspätung",            en: "delay" },
  { id: 85,  rank: 85,  de: "die Verbindung",            en: "connection" },
  { id: 86,  rank: 86,  de: "der Fahrplan",              en: "timetable / schedule" },
  { id: 87,  rank: 87,  de: "die Abfahrt",               en: "departure" },
  { id: 88,  rank: 88,  de: "die Ankunft",               en: "arrival" },
  { id: 89,  rank: 89,  de: "der Koffer",                en: "suitcase" },
  { id: 90,  rank: 90,  de: "das Gepäck",                en: "luggage / baggage" },
  { id: 91,  rank: 91,  de: "der Reisepass",             en: "passport" },
  { id: 92,  rank: 92,  de: "das Visum",                 en: "visa" },
  { id: 93,  rank: 93,  de: "die Unterkunft",            en: "accommodation" },
  { id: 94,  rank: 94,  de: "die Reservierung",          en: "reservation / booking" },
  { id: 95,  rank: 95,  de: "die Reiseversicherung",     en: "travel insurance" },

  // ── Rank 96–112: Shopping & money ───────────────────────────────────
  { id: 96,  rank: 96,  de: "das Geschäft",              en: "shop / store / business" },
  { id: 97,  rank: 97,  de: "der Supermarkt",            en: "supermarket" },
  { id: 98,  rank: 98,  de: "der Preis",                 en: "price" },
  { id: 99,  rank: 99,  de: "die Rechnung",              en: "bill / invoice" },
  { id: 100, rank: 100, de: "die Quittung",              en: "receipt" },
  { id: 101, rank: 101, de: "das Konto",                 en: "bank account" },
  { id: 102, rank: 102, de: "die Überweisung",           en: "bank transfer" },
  { id: 103, rank: 103, de: "die Kreditkarte",           en: "credit card" },
  { id: 104, rank: 104, de: "das Bargeld",               en: "cash" },
  { id: 105, rank: 105, de: "der Rabatt",                en: "discount" },
  { id: 106, rank: 106, de: "das Angebot",               en: "offer / deal" },
  { id: 107, rank: 107, de: "die Steuer",                en: "tax" },
  { id: 108, rank: 108, de: "die Öffnungszeiten",        en: "opening hours" },
  { id: 109, rank: 109, de: "die Kasse",                 en: "cash register / checkout" },
  { id: 110, rank: 110, de: "der Einkauf",               en: "shopping / purchase" },
  { id: 111, rank: 111, de: "der Markt",                 en: "market" },
  { id: 112, rank: 112, de: "die Rückgabe",              en: "return / refund" },

  // ── Rank 113–130: Home & living ──────────────────────────────────────
  { id: 113, rank: 113, de: "die Miete",                 en: "rent" },
  { id: 114, rank: 114, de: "der Vermieter",             en: "landlord" },
  { id: 115, rank: 115, de: "die Kaution",               en: "security deposit" },
  { id: 116, rank: 116, de: "die Nebenkosten",           en: "utility costs / extra costs" },
  { id: 117, rank: 117, de: "die Küche",                 en: "kitchen" },
  { id: 118, rank: 118, de: "das Badezimmer",            en: "bathroom" },
  { id: 119, rank: 119, de: "das Schlafzimmer",          en: "bedroom" },
  { id: 120, rank: 120, de: "das Wohnzimmer",            en: "living room" },
  { id: 121, rank: 121, de: "der Kühlschrank",           en: "refrigerator / fridge" },
  { id: 122, rank: 122, de: "der Herd",                  en: "stove / cooker" },
  { id: 123, rank: 123, de: "die Waschmaschine",         en: "washing machine" },
  { id: 124, rank: 124, de: "die Heizung",               en: "heating" },
  { id: 125, rank: 125, de: "der Aufzug",                en: "elevator / lift" },
  { id: 126, rank: 126, de: "der Schlüssel",             en: "key" },
  { id: 127, rank: 127, de: "der Nachbar",               en: "neighbour / neighbor" },
  { id: 128, rank: 128, de: "der Keller",                en: "cellar / basement" },
  { id: 129, rank: 129, de: "der Balkon",                en: "balcony" },
  { id: 130, rank: 130, de: "die Anmeldung",             en: "registration" },

  // ── Rank 131–148: Leisure & culture ─────────────────────────────────
  { id: 131, rank: 131, de: "die Freizeit",              en: "free time / leisure" },
  { id: 132, rank: 132, de: "das Hobby",                 en: "hobby" },
  { id: 133, rank: 133, de: "der Verein",                en: "club / association" },
  { id: 134, rank: 134, de: "das Museum",                en: "museum" },
  { id: 135, rank: 135, de: "das Theater",               en: "theatre / theater" },
  { id: 136, rank: 136, de: "das Konzert",               en: "concert" },
  { id: 137, rank: 137, de: "die Ausstellung",           en: "exhibition" },
  { id: 138, rank: 138, de: "das Kino",                  en: "cinema / movie theater" },
  { id: 139, rank: 139, de: "der Sport",                 en: "sport" },
  { id: 140, rank: 140, de: "das Schwimmbad",            en: "swimming pool" },
  { id: 141, rank: 141, de: "die Veranstaltung",         en: "event" },
  { id: 142, rank: 142, de: "die Einladung",             en: "invitation" },
  { id: 143, rank: 143, de: "der Geburtstag",            en: "birthday" },
  { id: 144, rank: 144, de: "die Feier",                 en: "celebration / party" },
  { id: 145, rank: 145, de: "der Spaziergang",           en: "walk / stroll" },
  { id: 146, rank: 146, de: "die Mannschaft",            en: "team" },
  { id: 147, rank: 147, de: "das Spiel",                 en: "game / match" },
  { id: 148, rank: 148, de: "die Meisterschaft",         en: "championship" },

  // ── Rank 149–163: Nature & environment ──────────────────────────────
  { id: 149, rank: 149, de: "die Umwelt",                en: "environment" },
  { id: 150, rank: 150, de: "die Natur",                 en: "nature" },
  { id: 151, rank: 151, de: "die Energie",               en: "energy" },
  { id: 152, rank: 152, de: "der Müll",                  en: "rubbish / garbage / waste" },
  { id: 153, rank: 153, de: "das Recycling",             en: "recycling" },
  { id: 154, rank: 154, de: "der Klimawandel",           en: "climate change" },
  { id: 155, rank: 155, de: "der Wald",                  en: "forest / woods" },
  { id: 156, rank: 156, de: "der Berg",                  en: "mountain" },
  { id: 157, rank: 157, de: "der Fluss",                 en: "river" },
  { id: 158, rank: 158, de: "das Meer",                  en: "sea / ocean" },
  { id: 159, rank: 159, de: "die Luft",                  en: "air" },
  { id: 160, rank: 160, de: "das Tier",                  en: "animal" },
  { id: 161, rank: 161, de: "die Pflanze",               en: "plant" },
  { id: 162, rank: 162, de: "der Vogel",                 en: "bird" },
  { id: 163, rank: 163, de: "der Boden",                 en: "ground / soil / floor" },

  // ── Rank 164–180: Society, admin & technology ───────────────────────
  { id: 164, rank: 164, de: "die Behörde",               en: "authority / government office" },
  { id: 165, rank: 165, de: "das Formular",              en: "form" },
  { id: 166, rank: 166, de: "der Ausweis",               en: "ID card" },
  { id: 167, rank: 167, de: "die Genehmigung",           en: "permit / permission" },
  { id: 168, rank: 168, de: "die Nachrichten",           en: "news" },
  { id: 169, rank: 169, de: "die Zeitung",               en: "newspaper" },
  { id: 170, rank: 170, de: "das Internet",              en: "internet" },
  { id: 171, rank: 171, de: "die E-Mail",                en: "email" },
  { id: 172, rank: 172, de: "das Handy",                 en: "mobile phone / cell phone" },
  { id: 173, rank: 173, de: "die Webseite",              en: "website" },
  { id: 174, rank: 174, de: "der Computer",              en: "computer" },
  { id: 175, rank: 175, de: "das Passwort",              en: "password" },
  { id: 176, rank: 176, de: "die Gesellschaft",          en: "society" },
  { id: 177, rank: 177, de: "die Wahl",                  en: "election / choice" },
  { id: 178, rank: 178, de: "der Bürger",                en: "citizen" },
  { id: 179, rank: 179, de: "das Recht",                 en: "right / law" },
  { id: 180, rank: 180, de: "das Ehrenamt",              en: "volunteer work" },
];
